version: "3.8"
services: 
  ui:
    build: ./trivial-ui
    # location of dockerfile
    container_name: ui_container
    ports:
      - '3000:3000'
    volumes:
      - ./trivial-ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true # opposite of detatched mode
  api:
    build: ./trivial-api
    # location of dockerfile
    container_name: api_container
    ports:
      - '4000:4000'
    volumes:
      - ./trivial-api:/app
      - /app/node_modules
  